### ISSUE TITLE
Find a strategy for authenticating

### ISSUE THREAD

**Issue by benjamin-thomas** [gothinkster/realworld-e2e-tests#5]
We don't control the backend.

We also don't want to hard code credentials as that could potentially lead to test failures.

Plus we'd probably want a clean slate on every suite run.

And the backend behind https://demo.realworld.io gets most probably reset every x hours...

So with these considerations in mind, we could maybe login with this strategy:

- Username (must be unique): `$UUID`
- Email (must be unique): `$UUID@example.com`
- Password: `$UUID`

@ChrisZie @geromegrignon any thoughts on this?

**Comment by geromegrignon** [comment]
That's somehow what we use for the Postman collection used to test the API currently:

Username (must be unique): local session id + new Date().toSeconds
Email (must be unique):  local session id@example.com
Password: 'password'

I like your solution @benjamin-thomas except for the password as we'll more likely add constraints on it to encourage strong passwords. We can include the UUID in a semi hardcoded password.

**Comment by benjamin-thomas** [comment]
Ok, adding a few hard coded chars at the end of the password sounds good to me

**Comment by benjamin-thomas** [comment]
@geromegrignon, can you send me an invitation to join the gothinkster org again please?

I want to push a commit and realize I missed the original invitation email :p

Thanks

**Comment by geromegrignon** [comment]
> @geromegrignon, can you send me an invitation to join the gothinkster org again please?
> 
> I want to push a commit and realize I missed the original invitation email :p
> 
> Thanks

Done :)

**Comment by benjamin-thomas** [comment]
Working around this issue via API stubbing for now.
