### ISSUE TITLE
Demo alternative specs

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld-e2e-tests#7]
## Description

We lately faced unrelated and unwanted content being displayed on the demo.
To provide a safe and healthy experience for everyone, the only scalable solution to prevent such a situation has been to prevent users to see everyone else's content: you can only see your content and demo account one.

But it comes at a price: the demo doesn't follow the backend specs.

In the documentation, I encourage people to use this version if they plan to publicly host/use an API.

Depending on the way to organize tests, it might not have consequences: After adding content and singing out, you can't see your articles/comments and the tags you created.

**Comment by benjamin-thomas** [comment]
Noted. I'm closing this since I think I'll be alright stubbing the API responses as much as possible.

I should be able to create my own scenarios that way but I'll have to see if that works out okay in practice :p
